# Generated by Django 5.2 on 2025-05-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0005_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alert_images/'),
        ),
    ]
