# Generated by Django 5.2 on 2025-05-21 00:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0009_rename_posted_at_emergencyalert_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='announcement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bulletin.announcement'),
            preserve_default=False,
        ),
    ]
