# Generated by Django 5.2 on 2025-05-21 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0010_feedback_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='announcement',
        ),
    ]
