# Generated by Django 5.2 on 2025-05-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0012_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('done', 'Done')], default='ongoing', max_length=20),
        ),
    ]
