# Generated by Django 5.2 on 2025-05-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0013_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
